### ISSUE TITLE
Eludris bad

### ISSUE THREAD

**Issue by EnokiUN** [eludris/eludris#32]
### What is the issue?

eludris very bad

### What is the issue with?

None

### Checks

- [X] Have you checked the documentation?
- [X] Have you checked other issues to make sure this is not a duplicate?

### Minimum Reproducible Sample/Code

mid tbh

**Comment by ooliver1** [comment]
Minimal reproducible code SIGSEGV'd, cannot reproduce.

**Comment by EnokiUN** [comment]
> Minimal reproducible code SIGSEGV'd, cannot reproduce.

SEE, SO BAD YOU CAN'T EVEN RUN CODE WITHOUT IT FUCKING IMPLODING

**Comment by ooliver1** [comment]
Nah man, pandemonium just die_kys' every few weeks.
