### ISSUE TITLE
v0.4

### ISSUE THREAD

**Issue by EnokiUN** [eludris/eludris#34]
# This is the meta-issue for Eludris v0.4.

All major developments and roadmaps will be here until v0.4 is out and this version is closed.

You may want to watch this issue.

## Goals

Eludris v0.4 -- or just known as the features update -- aims to provide "actual features" with the aim of making Eludris more usable.

These features include stuff from accounts to posts and even reactions.
All of these features are to be implemented in a way that does not majorly obstruct v0.5 (federation & e2ee) update.

This will also include a major change to our currently (nonexistent) docs structure to include autodoc and other enhancement. This will also entail a rewrite and a move-over from mdBook to our own custom creation.

## Pre-Roadmap (v0.3.3)

- [x] Docs v2 (#37, #66)
- [x] Post-Docs v2 Code refactor (#57, #60, #61, #62, #63, #64, #65, #68, #70)
- [x] Tests v2 (#67)

### 

- [ ] Accounts (auth (:D))
- [ ] Permissions
- [ ] Communities
    - [ ] Message communities
        - [ ] Channels
    - [ ] Post communities
- [ ] Roles
- [ ] DMs & GDMs
- [ ] Embed service & media proxy
- [ ] Embeds and message attachments
- [ ] Emojis
- [ ] Bots
- [ ] Voice & Screenshare

[Gist](https://gist.github.com/EnokiUN/e16a1feb547e293e40b875bdad0aa256)

**Comment by VincentRPS** [comment]
@EnokiUN what's the scope for 0.4?

**Comment by EnokiUN** [comment]
> @EnokiUN what's the scope for 0.4?

Updated the issue (yesterday)

**Comment by VincentRPS** [comment]
> > @EnokiUN what's the scope for 0.4?
> 
> Updated the issue (yesterday)

Ah so it's absolutely massive I see

**Comment by EnokiUN** [comment]
> > > @EnokiUN what's the scope for 0.4?
> > 
> > 
> > Updated the issue (yesterday)
> 
> Ah so it's absolutely massive I see

Yep, stupendously so

**Comment by ooliver1** [comment]
uh.
